### PR TITLE
Update OfflineEdgeHandler.java

### PR DESCRIPTION
**Pull request by Sn0w3y**
Update OfflineEdgeHandler.java so it checks for Offline Edges on a given Schedule

### CODE REVIEW

**Comment by sfeilmeier** [comment]
@Sn0w3y: Is this ready for review?

**Comment by Sn0w3y** [comment]
> @Sn0w3y: Is this ready for review?

Yes aswell ! :) Maybe share your thoughts please

**Comment by da-Kai** [comment]
@Sn0w3y, checking metadata in a cycle is not necessary.

Metadata has to be checked once at the beginning, to get the initial state. After that, the "ON_SET_OFFLINE" event is used to detect if a edge goes offline.

Check:
https://github.com/OpenEMS/openems/pull/2506/files#diff-01e94d7b33c6179437e5972b14591d6e5e9c4a23e87c1fedeb0661e0187b8b4aL244-R289

**Comment by Sn0w3y** [comment]
@da-Kai thanks for clearifying this !

**Comment by Sn0w3y** [comment]
@da-Kai am I seeing this wrong or is there no ON_SET_OFFLINE event:

		case Edge.Events.ON_SET_ONLINE:
			yield this::handleOnSetOnline;

		case Metadata.Events.AFTER_IS_INITIALIZED:
			yield this::handleMetadataAfterInitialize;

**Comment by da-Kai** [comment]
> @da-Kai am I seeing this wrong or is there no ON_SET_OFFLINE event:
> 
> ```
> 	case Edge.Events.ON_SET_ONLINE:
> 		yield this::handleOnSetOnline;
> 
> 	case Metadata.Events.AFTER_IS_INITIALIZED:
> 		yield this::handleMetadataAfterInitialize;
> ```

You are right. The "ON_SET_ONLINE" event is called, every time the online state of an edge changes and contains a boolean with the current online state.

see:
https://github.com/OpenEMS/openems/blob/develop/io.openems.backend.common/src/io/openems/backend/common/metadata/Edge.java#L247-L252
```Java
		public static final String ON_SET_ONLINE = Events.TOPIC_BASE + "ON_SET_ONLINE";

		public static final class OnSetOnline {
			public static final String EDGE_ID = "EdgeId:String";
			public static final String IS_ONLINE = "IsOnline:boolean";
		}
```

**Pull request closed without merging**
