### PR TITLE
fix: use tailing comma to always-multiline

### PR DESCRIPTION
**Pull request by miettal**
eslint src/ --fix

1. Typically, using trailing comma minimize diff and easy to review, merging.
2. on the other hand, snipping trailing comma has compatibility old javascript implementation.

in this project, /ui codes are using typescript so its not need to care about 2.
so I changed tailing comma style.

### CODE REVIEW

**Review by sfeilmeier — APPROVED** [review]

**Comment by sfeilmeier** [comment]
I fully agree with your reasoning and approach. Thanks for the contribution! 👍

**Review by sfeilmeier — CHANGES_REQUESTED** [review]
Unfortunately there are merge conflicts now and I do not have write permissions on your branch. Please fix and request review again. Thanks!

**Comment by miettal** [comment]
Thank you for review, I'll rebase this PR to latest commit.

**Review by sfeilmeier — APPROVED** [review]

**Comment by lukasrgr** [comment]
@miettal i dont agree, that this will be easier to review, reducing it from a two line change to one line doesnt make it easier, why is this change necessary?

**Comment by miettal** [comment]
Typically less diff makes it easier to review.
and it help to keeping line history(like git blame).

**Comment by miettal** [comment]
@lukasrgr I found good material of trailing comma explanation! this is easy to understand!
https://medium.com/@nikgraf/why-you-should-enforce-dangling-commas-for-multiline-statements-d034c98e36f8

**Comment by lukasrgr** [comment]
@miettal im not fully convinced but if reviewing etc. is really an issue for others, then i have to agree

**Comment by miettal** [comment]
// there are many code styling and mindset of code styling. no right way and it's also depends on environment / project. Anyway let's experience with everyone!

**Comment by ikegam** [comment]
Jump in from same company as @miettal,

"trailing comma" is just a style for keeping same style for every lines.
Traditional language like C, enum of Java can not support this style but js can support so we made this PR. It can make unified diff for all elements in structure. W/o trailing comma, if we touch last element it makes two lines, but middle line makes only one line as you know. This is only advanced point as I know.

We, Girasol Energy, are just downstream of yours so we will follow your decision.

BTW, just my feeling, it seems mixed up in same directory with different newline code which are /n and /r/n is more likely to be fixed I guess.

**Comment by ikegam** [comment]
Just I asked @miettal to rebase and modify LF / CRLF related PR. please wait some days.

**Pull request merged**
