### PR TITLE
Include keys in components object in edge config

### PR DESCRIPTION
**Pull request by jpdark**
The id is a property of the model that is represented by each object, so including it in that representation is desirable.
Same goes for the channels when included in the components.

This benefits (de)serialization in clients for the edge config api.

### CODE REVIEW

**Comment by hydroid7** [comment]
Hi there,
the changes look ok to me.

Can you please elaborate a bit why this change is useful?
Do you plan any feature that depend on the `id`s?

Increasing the API surface should be done only after a discussion :)

**Comment by jpdark** [comment]
@hydroid7 Would love to hear what you think. Keen to merge (or close) this PR.

**Review by hydroid7 — CHANGES_REQUESTED** [review]
Hi,
thank you for pushing this 😄 . IMHO the PR is a little bit small now.
Please also document your changes in the docs for other to be able to find it.

**Comment by jpdark** [comment]
Thanks @hydroid7. I'm not 100% sure what you are requesting. My understanding is that you would like:
- a larger PR (🤔 ?)
- additional documentation for `getEdgeConfig` rpc

I hope to address both with 2 additional commits.
Thanks.

**Review by hydroid7 — APPROVED** [review]

**Comment by hydroid7** [comment]
Thank you for the docs, it looks good.

**Pull request closed without merging**
