### PR TITLE
Fix Translations

### PR DESCRIPTION
**Pull request by Sn0w3y**

### CODE REVIEW

**Review by sfeilmeier — CHANGES_REQUESTED** [review]
This breaks translations, because you did not update the actual translation files (`de.json`, `en.json`, etc.)

**Comment by Sn0w3y** [comment]
> This breaks translations, because you did not update the actual translation files (`de.json`, `en.json`, etc.)

AFAIK in your last Backport to Fems it was already included in Uppercase @sfeilmeier

**Comment by sfeilmeier** [comment]
No. This is in latest `develop`:

https://github.com/OpenEMS/openems/blob/develop/ui/src/assets/i18n/de.json#L15
```
  "Edge": {
    "Index": {
      "EmergencyReserve": {
        "InfoForEmergencyReserveSlider": "Durch Aktivieren kann eine Notstromreserve zwischen 5 % und 100 % der Batteriekapazität eingestellt werden.",
        "emergencyReserve": "Notstromreserve"
      },
```

**Comment by Sn0w3y** [comment]
> No. This is in latest `develop`:
> 
> https://github.com/OpenEMS/openems/blob/develop/ui/src/assets/i18n/de.json#L15
> 
> ```
>   "Edge": {
>     "Index": {
>       "EmergencyReserve": {
>         "InfoForEmergencyReserveSlider": "Durch Aktivieren kann eine Notstromreserve zwischen 5 % und 100 % der Batteriekapazität eingestellt werden.",
>         "emergencyReserve": "Notstromreserve"
>       },
> ```

Very sorry for this oversight, i don't know why i had it in Uppercase - will change it in the files and provide it again.. 

Again, sorry @sfeilmeier

**Comment by Sn0w3y** [comment]
@sfeilmeier done now ! sorry again for the inconvenience !

**Comment by Sn0w3y** [comment]
@sfeilmeier the last Commit is indeed not correct in the Develop right now :)

**Review by sfeilmeier — APPROVED** [review]

**Pull request merged**
