### PR TITLE
UI: Fix - EvcsModal - Uncaught (in promise): TypeError: this.controller is undefined

### PR DESCRIPTION
**Pull request by DerStoecki**
Description:

When configuring an EVCS component w.o. an evcsController and clicking the FlatWidget, the ModalComponent tries to resolve a non existing controller, therefore resulting in an uncaught promise and showing a blank modal.

Fix: 
Added null checks.

### CODE REVIEW

**Comment by lukasrgr** [comment]
@DerStoecki hi, can you resolve this conflict and then i will approve, does this happen that the controller is null? 

Shouldnt be happening 😄

**Comment by DerStoecki** [comment]
> @DerStoecki hi, can you resolve this conflict and then i will approve, does this happen that the controller is null?
> 
> Shouldnt be happening 😄

@lukasrgr hey there,

This happened when we activated an evcs via "install component" w.o. an evcs controller. 
The modal was just a blank canvas and the inspector showed the issue (controller is undefined)
There might be a different underlying issue here, but after I'd implemented those null checks, the modal component showed up perfectly fine.

After fixes the modal component became:
AfterFix

**Comment by lukasrgr** [comment]
@DerStoecki i will approve, thanks for your contribution, what is the current state about the appCenter sequence diagramm btw?

**Comment by DerStoecki** [comment]
> @DerStoecki i will approve, thanks for your contribution, what is the current state about the appCenter sequence diagramm btw?

thank you

I'll get back to you regarding the sequence diagramm.
I'll discuss this with @clehne tomorrow if it's better to give you access to our wiki so you can double check the diagramm or if I should post this in the forum, where we can discuss the diagramm further.

**Comment by DerStoecki** [comment]
> @DerStoecki i will approve, thanks for your contribution, what is the current state about the appCenter sequence diagramm btw?

Hey @lukasrgr 

We gave you access to our [Wiki](https://support.coworking.openems.cloud/projects/openems-incubator/wiki/AppCenter)
(Same as hackathon but different project)
There I added some draw.io diagrams of the AppCenter Sequence diagramm. We should check if this is correct etc and use this as a base line for the doc.

There are also more entries for you to check like [UI-Overview](https://support.coworking.openems.cloud/projects/openems-incubator/wiki/Architektur_%C3%9Cbersicht) or the [Live Flatwidget](https://support.coworking.openems.cloud/projects/openems-incubator/wiki/FlatWidget)
which we can use as an inspiration / base lvl for documentation stuff as well if its suitable.

**Review by lukasrgr — APPROVED** [review]

**Review by sfeilmeier — APPROVED** [review]
Approved. But I would appreciate if you could fix the issues in a separate PR. We will need to fix all of those little bugs latest once we activate `strict mode`. (https://www.typescriptlang.org/tsconfig#strict)

**Pull request merged**
