### PR TITLE
Extended Intellij Config with Reformater

### PR DESCRIPTION
**Pull request by TimStoecker**
Extended the Intellij Config with the 'Adapter for Eclipse code Formatter'. This changes the behavior of inellij's build-in Reformat Code functionality, to use the one in eclipse.

### CODE REVIEW

**Comment by hydroid7** [comment]
Hi, 
thank you improving IDEA support :)
OpenEMS uses Checkstyle for formatting the code. 
Would a checkstyle plugin work for IDEA?

https://plugins.jetbrains.com/plugin/1065-checkstyle-idea

**Comment by DerStoecki** [comment]
Hello hello, 
this is what we are working with actually. however the pure formatting/indentation of the code differs from what eclipse is using.

Therefore: 
Checkstyle for general checks : (Missing Comments, variable declarations etc etc) 
but for indentations use this eclipse plugin (makes it far easier for Eclipse users to check/review IntelliJ code)

**Review by hydroid7 — APPROVED** [review]
I went through the process and was able to format the code like with Eclipse. Approved.

**Comment by hydroid7** [comment]
@DerStoecki BTW, it would be nice to see a guide how to get up and running OpenEMS with IDEA. 😄

**Comment by DerStoecki** [comment]
@hydroid7 Do you mean the same way as in Eclipse where you can say "run osgi bundle" or something like that?

If so, we can add that too in another PR

**Comment by hydroid7** [comment]
Yes, that would be great!

**Review by sfeilmeier — COMMENTED** [review]
Thank you guys for improving and reviewing the docs!

**Pull request merged**
