### PR TITLE
Backend: Common + Metadata: Refactored Name of AlertingSetting to UserAlertingSettings

### PR DESCRIPTION
**Pull request by DerStoecki**
This is just a refactor of the Name AlertingSetting to UserAlertingSettings. This does not provide any functionality, but will improve the readability of the SumStateAlert PR in the future. 

This commit is one of many prepare PRs / commits for a bigger PR: SumStateAlert #2260
By separating the big #2260 into smaller commits we would like to make the review easier.

Co-authored-by: Kai Jeschek [99220919+da-Kai@users.noreply.github.com](mailto:99220919+da-Kai@users.noreply.github.com)

### CODE REVIEW

**Review by clehne — APPROVED** [review]
Ok. Just the refactored UserAlertingSettings.

**Comment by da-Kai** [comment]
I see no necessity for this pull request. But I wouldn't mind it either.
what is your opinion @sfeilmeier?

**Comment by sfeilmeier** [comment]
@da-Kai: it's up to you as you know the code best. If you decide to deny it, it's ok for me 👍

**Review by da-Kai — APPROVED** [review]

**Review by sfeilmeier — APPROVED** [review]

**Comment by sfeilmeier** [comment]
Please fix conflicts

**Comment by clehne** [comment]
Hi @da-Kai, same for @DerStoecki and me. It is up to you! Please close this PR if you prefer to handle it in #2260.

**Comment by da-Kai** [comment]
@clehne @DerStoecki @sfeilmeier This is okay for me 👍

**Review by sfeilmeier — APPROVED** [review]

**Pull request merged**
