### PR TITLE
WebSocket: enable permessage-deflate to communication

### PR DESCRIPTION
**Pull request by miettal**
This PR changes websocket communication use compression.

cf.

 - https://datatracker.ietf.org/doc/html/rfc7692
 - https://github.com/TooTallNate/Java-WebSocket/blob/master/src/main/example/PerMessageDeflateExample.java

### CODE REVIEW

**Comment by miettal** [comment]
320791082-1d4b9e0c-4323-447e-a4be-786df59a14f1
↓
320791138-3ef3b45f-8d81-4914-a08b-f764a9cc241d

**Comment by Sn0w3y** [comment]
Just because I am curious - isn't this a breaking change as the Backend also uses the Websocket Class and the Edge also does it - if i have some Devices not using the Changes (e.g. if a Device has an older Version) will it still work ?

**Comment by Sn0w3y** [comment]
WOW ! @sfeilmeier this improves Loading Speeds a lot ! Channels get updated more frequently etc.

**Comment by sfeilmeier** [comment]
Great! Thanks for the contribution, I did not know about this.

Just to be sure, without testing it myself: Is this feature backwards compatible, i.e. do the following scenarios work?

- [ ] **Client without** permessage-deflate -> connecting to **Server with** permessage-deflate
- [ ] **Client with** permessage-deflate -> connecting to **Server with** permessage-deflate
- [ ] **Client with** permessage-deflate -> connecting to **Server without** permessage-deflate

**Comment by Sn0w3y** [comment]
Interestingly I also asked myself this question :D

I updated my Backend and ONE Device and vice-versa.
Outcome:

> * **Client without** permessage-deflate -> connecting to **Server with** permessage-deflate

Can confirm

> * [ ]  **Client with** permessage-deflate -> connecting to **Server with** permessage-deflate
> *

Can confirm

> * **Client with** permessage-deflate -> connecting to **Server without** permessage-deflate

Can confirm

**Comment by sfeilmeier** [comment]
Thank you @Sn0w3y!

**Review by sfeilmeier — APPROVED** [review]

**Comment by Sn0w3y** [comment]
@miettal Sometimes it comes to:

`May 25 19:24:57 java[25091]: 2024-05-25T19:24:57,973 [orker-80] ERROR [g.java_websocket.WebSocketImpl] Closing due to invalid data in frame
May 25 19:24:57 java[25091]: org.java_websocket.exceptions.InvalidDataException: invalid distance too far back
May 25 19:24:57 java[25091]:         at org.java_websocket.extensions.permessage_deflate.PerMessageDeflateExtension.decodeFrame(PerMessageDeflateExtension.java:181) ~[?:?]
May 25 19:24:57 java[25091]:         at org.java_websocket.drafts.Draft_6455.translateSingleFrame(Draft_6455.java:589) ~[?:?]
May 25 19:24:57 java[25091]:         at org.java_websocket.drafts.Draft_6455.translateFrame(Draft_6455.java:744) ~[?:?]
May 25 19:24:57 java[25091]:         at org.java_websocket.WebSocketImpl.decodeFrames(WebSocketImpl.java:399) ~[?:?]
May 25 19:24:57 java[25091]:         at org.java_websocket.WebSocketImpl.decode(WebSocketImpl.java:234) ~[?:?]
May 25 19:24:57 java[25091]:         at org.java_websocket.server.WebSocketServer$WebSocketWorker.doDecode(WebSocketServer.java:1114) ~[?:?]
May 25 19:24:57 java[25091]:         at org.java_websocket.server.WebSocketServer$WebSocketWorker.run(WebSocketServer.java:1086) ~[?:?]
May 25 19:24:57 java[25091]: 2024-05-25T19:24:57,977 [socket-7] WARN  [.backend.edgewebsocket.OnError] [Edge.Websocket] Websocket error. InvalidDataException: invalid distance too far back
May 25 19:24:57 java[25091]: org.java_websocket.exceptions.InvalidDataException: invalid distance too far back
May 25 19:24:57 java[25091]:         at org.java_websocket.extensions.permessage_deflate.PerMessageDeflateExtension.decodeFrame(PerMessageDeflateExtension.java:181)
May 25 19:24:57 java[25091]:         at org.java_websocket.drafts.Draft_6455.translateSingleFrame(Draft_6455.java:589)
May 25 19:24:57 java[25091]:         at org.java_websocket.drafts.Draft_6455.translateFrame(Draft_6455.java:744)
May 25 19:24:57 java[25091]:         at org.java_websocket.WebSocketImpl.decodeFrames(WebSocketImpl.java:399)
May 25 19:24:57 java[25091]:         at org.java_websocket.WebSocketImpl.decode(WebSocketImpl.java:234)
May 25 19:24:57 java[25091]:         at org.java_websocket.server.WebSocketServer$WebSocketWorker.doDecode(WebSocketServer.java:1114)
May 25 19:24:57 java[25091]:         at org.java_websocket.server.WebSocketServer$WebSocketWorker.run(WebSocketServer.java:1086)
May 25 19:24:57 java[25091]: 2024-05-25T19:24:57,990 [socket-8] INFO  [.backend.edgewebsocket.OnClose] [Edge.Websocket] Disconnected. Code [1008] Reason [invalid distance too far back]
`

How could we solve this?

**Comment by miettal** [comment]
I'm not expert of java and websocket, but I guess the possibility are ...

 - TooTallNate/Java-WebSocket has de-initialization process bug.
 - TooTallNate/Java-WebSocket has decoding(protocol implementation) bug
 - client side encoding(protocol implementation) bug
 
if the problem happens in specific devices, Could you share it?

**Comment by Sn0w3y** [comment]
if the problem happens in specific devices, Could you share it?

BeagleBone Black - last recent OpenEMS Version - but i do not think it is replicable as i told you the WiFi Connection is very low at the place where the device is Conneted to :)

**Comment by miettal** [comment]
hmmm, Thanks information. I also try/investigate to this kind log my server.

**Pull request merged**
