### PR TITLE
Several improvements in the REST API

### PR DESCRIPTION
**Pull request by martingruening**
- Made connection limit configurable
- Made channel output in GET requests more comprehensive and inline with EdgeConfig
- Deliver the approriate response code for authentication errors
- Enable multiple-at-once channel readings as a JSON Array

### CODE REVIEW

**Comment by martingruening** [comment]
Solves issues: #1347 #1348 #1350 #1351

**Comment by martingruening** [comment]
Corrected scale factors for Voltage, Current and Frequency in Sunny Home Manager 2.0 Meter implementation

**Review by sfeilmeier — APPROVED** [review]
Thanks Martin, these are some very good improvements. I have no comments or improvement suggestions on the code quality.

Just want to point out two things:
1. I personally like Regex a lot, but I also feel that many people have problems understanding them. Because of this I am introducing a `matchWildcard` method in my "Implement a Prediction architecture" branch (#1327), that uses well known 'asterisk' approach. It's by far not as flexible as Regex, but I wonder if it could not be an option here. https://github.com/OpenEMS/openems/blob/724c20af2c37a98893961394e9402b9c11cc0be8/io.openems.common/src/io/openems/common/utils/StringUtils.java#L46
2. Have you heard about GraphQL? It is a query language for REST calls that follows the same idea of yours - to reduce calls by joining them. Do you think going that way would be a better approach? (https://graphql.org/)

**Comment by martingruening** [comment]
Thanks for the review and your remarks.

Regarding RegEx: I believe that anybody that can call REST APIs and parse JSON can understand RegExp to a certain degree. And if you only know that `.*` is a wildcard, that can be enough to get a multiple-in-one query quickly going. So I am quite happy with the RegExp approach - it gives power to people who can create complex RegExp and give simplicity to those who just know the simplest RegExp wildcard string.

I have never heard of GraphQL. My initial thought was that it might be overengineering for my use case, but I might be wrong.  I recently started to build an OpenEMS binding for OpenHAB. Initially I wanted to use the REST API to frequently poll the channels, but now I'm investigating the JSON-RPC Websocket as a better way for integration.

**Comment by sfeilmeier** [comment]
Ok - yes, I agree. It's good to have your opinion on that. I might also rethink the approach in the other branch. GraphQL sounded to be a very generic approach on solving these kind of problems. But I am also not sure how widely used it is and if it is worth the effort.

Ping me if you need support on the JSON-RPC topic. There is some documentation here: https://openems.github.io/openems.io/openems/latest/component-communication/index.html#_subscribe_to_channels

You have to send a JSON-RPC "SubscribeChannelsRequest" and from then on you will receive "CurrentDataNotifications". See the UI for an example:

- Send the request:
https://github.com/OpenEMS/openems/blob/develop/ui/src/app/shared/edge/edge.ts#L149-L154

- Definition of the request:
https://github.com/OpenEMS/openems/blob/e19f80d01148e336eec6cfc4985198e98960f69a/ui/src/app/shared/jsonrpc/request/subscribeChannelsRequest.ts#L10-L18

- Handling of the CurrentDataNotifications:
https://github.com/OpenEMS/openems/blob/develop/ui/src/app/shared/edge/edge.ts#L175

- Definition of the notification:
https://github.com/OpenEMS/openems/blob/e19f80d01148e336eec6cfc4985198e98960f69a/ui/src/app/shared/jsonrpc/notification/currentDataNotification.ts#L8-L14

**Pull request merged**
