### PR TITLE
Add Edimax SP2101W V2 Device

### PR DESCRIPTION
**Pull request by hogmoff**
Added Device for a switchable socket with power meter

### CODE REVIEW

**Comment by hogmoff** [comment]
The Function is now ready for Review. Tested on Device Edimax SP2101W V2

**Comment by sfeilmeier** [comment]
Thank you. We'll try to review. Sorry for the delay. Is it really necessary to have "Solarradiationpredictormodell" in this pull-request as well?

**Comment by hogmoff** [comment]
> Thank you. We'll try to review. Sorry for the delay. Is it really necessary to have "Solarradiationpredictormodell" in this pull-request as well?

I'm new and this is my first experience with github flow. Of course, the "Solarradiationpredictormodell" isn't nescessary for this pull-request. I will remove the predictor.

**Comment by sfeilmeier** [comment]
Ok - great. No worries! 

Instead of deleting the files that you don't want to have in this pull-request (like your changes to EdgeApp.bndrun or within the ui directory) you should reset them to develop. In the git console you could use this command:

`git checkout develop io.openems.edge.application/EdgeApp.bndrun`

**Comment by hogmoff** [comment]
I've to say, that wasn't as easy as i thought. I hope you're not put off by all the commits. 
In the end, there are only four new files.

**Comment by sfeilmeier** [comment]
> I've to say, that wasn't as easy as i thought. I hope you're not put off by all the commits.
> In the end, there are only four new files.

No worries. For the first time everything seems confusing; it's getting better with time and experience :-)

I added some 'review' commits. Have a look at them individually if you are interested to see how I try to match the bundle with the rest of OpenEMS. I did not touch the actual code yet, though.

**Pull request closed without merging**
